version: "3"
services:
  php:
    build: ./php/
    ports:
      - "8080:80"
    volumes:
      - ./php/src:/var/www/html

  ssh:
    build: ./ssh/
    ports:
      - "9200:22"
    volumes:
      - storage:/root/.ssh
      - ssh_setting:/etc/ssh/

volumes:
  storage:
  ssh_setting: